### ISSUE TITLE
Maven.writeModel breaks some tests since v31

### ISSUE THREAD

**Issue by qmonmert** [fabric8-launcher/maven-model-helper#129]
Hey,

Since `v31` my tests are broken. I use `Maven.writeModel`.

![image](https://github.com/fabric8-launcher/maven-model-helper/assets/9989211/2039f9d5-e80d-42f0-bdd1-4a7e9aeef045)

(left: `v34`; right: `v30`)
There is a new line added (l33 since `v31`). Do you think that it is normal?

Thanks

**Comment by gastaldi** [comment]
Hi,do you have a small reproducer?

**Comment by qmonmert** [comment]
https://github.com/jhipster/jhipster-lite/pull/9270 🙂

**Comment by gastaldi** [comment]
Thanks, that shouldn't happen if you don't specify a XMLFormat (which is the case AFAIK), I'll investigate what's going on

**Comment by qmonmert** [comment]
Thanks, it seems a problem when dependencies are the same

**Comment by murdos** [comment]
@gastaldi : what our test does what be seen here:
https://github.com/jhipster/jhipster-lite/blob/09303e563d246b6bfbcb6ff78a007e47a66e74d5/src/test/java/tech/jhipster/lite/module/domain/JHipsterModulesFixture.java#L135
An additional managed dependency is added, and the first existing one is deleted. (There's also another addition of managed dependency, but since it already exists it's not added).

**Comment by murdos** [comment]
@gastaldi : here an additional test case with a dependency added between two existing ones: https://github.com/murdos/maven-model-helper/commit/9ede114aa2b81dab566f7d31328a3090405216ce#diff-692b3045ed57f028a4b7ae687236982c0cd5724b8acd85d9ddd0ce7333920596

It seems that if existing dependencies are separated by an empty line, an empty line is also added.
